version: '3'

services:
  web:
    build: .
    command: gunicorn weather_project.wsgi:application --bind 0.0.0.0:8007 --workers 4
    # command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8007:8007"
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"